### ISSUE TITLE
Make progress bar total instead of time left and total. 

### ISSUE THREAD

**Issue by Corey4005** [xuejianma/progresspanel#1]
Hey! Cool program! This solved a problem that I was having with regular progressbars in tkinter. I am curious if you could make the "Time Left" option a keyword argument to turn it off so that the text could just be a percent?

**Comment by xuejianma** [comment]
Thanks for the issue. Created a new attribute display_time_left. It's default to True but you can set it to False, so that the time remaining can be turned off. To use the new feature, please update the package (>=0.1.2) by running `pip install progresspanel --upgrade` and set `display_time_left=False` when creating an instance.
